import { FETCH_POSTS, NEW_POST } from "./types";

// dispatched action intercepted by Saga in `saga.js`
export const fetchPosts = () => dispatch => {
    dispatch({
        type: FETCH_POSTS,
        payload: ['DRD TEST'], // empty as initial value
    });
}

// dispatched action generated by action crerator and not currently intercepted by a saga
export const createPost = postData => dispatch => {
  console.log("DRD __ `createPost`");
  fetch("https://jsonplaceholder.typicode.com/posts", {
    method: "POST",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify(postData)
  })
    .then(response => response.json())
    .then(post =>
      dispatch({
        type: NEW_POST,
        payload: post
      })
    );
};
